import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { CartProvider } from "@/context/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <CartProvider>
        <body className="min-h-full flex flex-col">
          <header className="border-b border-gray-200 p-4 flex justify-center items-center">
            <nav className="flex gap-6">
              <Link href="/" className="hover:text-gray-600">
                Products
              </Link>{" "}
              <Link href="/contact" className="hover:text-gray-600">
                Contact
              </Link>{" "}
              <Link href="/cart" className="hover:text-gray-600">
                Cart
              </Link>
            </nav>
          </header>
          <main className="mx-auto w-full max-w-7xl px-4 py-8">{children}</main>
          <footer className="border-t border-gray-200 p-4 text-center">
            <p>&copy; Online shop</p>
          </footer>
        </body>
      </CartProvider>
    </html>
  );
}
