import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/context/CartContext";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <CartProvider>
        <body className="min-h-full flex flex-col">
          <Header />
          <main className="mx-auto w-full max-w-7xl px-4 py-8 min-h-screen">
            {children}
          </main>
          <footer className="border-t border-gray-200 p-4 text-center">
            <p>&copy; E&T Online shop</p>
          </footer>
        </body>
      </CartProvider>
    </html>
  );
}
